export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';

export const FETCH_USER_PLAYLISTS = 'FETCH_USER_PLAYLISTS';
export const SET_USER_PLAYLISTS = 'SET_USER_PLAYLISTS';
