export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';

export const FETCH_USER_PLAYLISTS = 'FETCH_USER_PLAYLISTS';
export const SET_USER_PLAYLISTS = 'SET_USER_PLAYLISTS';

export const FETCH_USER_RECENT_SONGS = 'FETCH_USER_RECENT_SONGS';
export const SET_USER_RECENT_SONGS = 'SET_USER_RECENT_SONGS';

export const SET_SELECTED_SONG = 'SET_SELECTED_SONG';
export const FETCH_SELECTED_SONG_FEATURES = 'FETCH_SELECTED_SONG_FEATURES';
export const SET_SELECTED_SONG_FEATURES = 'SET_SELECTED_SONG_FEATURES';